//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VerenigingenEntities2 : DbContext
    {
        public VerenigingenEntities2()
            : base("name=VerenigingenEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Categorie> Categorie { get; set; }
        public virtual DbSet<Contactpersoon> Contactpersoon { get; set; }
        public virtual DbSet<Event> Event { get; set; }
        public virtual DbSet<Gebruiker> Gebruiker { get; set; }
        public virtual DbSet<GebruikerVereniging> GebruikerVereniging { get; set; }
        public virtual DbSet<Vereniging> Vereniging { get; set; }
        public virtual DbSet<VerenigingCategorie> VerenigingCategorie { get; set; }
        public virtual DbSet<VerenigingContactpersoon> VerenigingContactpersoon { get; set; }
        public virtual DbSet<VerenigingEvent> VerenigingEvent { get; set; }
    }
}
