//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Event()
        {
            this.VerenigingEvent = new HashSet<VerenigingEvent>();
        }
    
        public int id { get; set; }
        public string titel { get; set; }
        public string telefoonnr { get; set; }
        public string beschrijving { get; set; }
        public string straat { get; set; }
        public string huisnr { get; set; }
        public string gemeente { get; set; }
        public string postcode { get; set; }
        public System.DateTime datum { get; set; }
        public decimal prijs { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VerenigingEvent> VerenigingEvent { get; set; }
    }
}
