//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gebruiker
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Gebruiker()
        {
            this.GebruikerVereniging = new HashSet<GebruikerVereniging>();
        }
    
        public int id { get; set; }
        public string email { get; set; }
        public string paswoord { get; set; }
        public bool admin { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GebruikerVereniging> GebruikerVereniging { get; set; }
    }
}
