//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VerenigingContactpersoon
    {
        public int id { get; set; }
        public int verenigingId { get; set; }
        public int contactpersoonId { get; set; }
    
        public virtual Contactpersoon Contactpersoon { get; set; }
        public virtual Vereniging Vereniging { get; set; }
    }
}
